Deployments to prod environment with fixed versions - Deployment to prod environment will now also be done for Git tags - Instead of just pull the (new) "latest" image, the deployment script will use the concrete version when a Git tag had been pushed. We rewrite the docker-compose.yaml definition which image version to use. - A note to THWIKI-92: This commit does not resolve the issue of deploying a wrong "latest" version when multiple (feature) pipelines produce different versions with the same tag. That is because I still want to be able to release a non-tagged master merge to production, without releasing it publicly. A future fix would need to distinguish a master-"latest" from a feature-"latest", e.g. by adding the branch name into the docker tag.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -128,13 +128,25 @@ deploy-test:
 deploy-prod:
   stage: deploy
   rules:
-    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
   image: alpine:3.20.2
-  script:
-    - apk add openssh
-    - mkdir -p ~/.ssh
-    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
-    - chmod 600 "$SSH_PRIVATE_KEY"
-    - ssh -i "$SSH_PRIVATE_KEY" "$SSH_LOGIN" "cd $DOCKER_DIRECTORY_PROD && docker compose pull && docker compose up -d"
+  script: |
+    if [ -z "$DOCKER_TAG" ]; then
+      echo "Error: DOCKER_TAG is not defined. Previous dockerize step should have set that."
+      exit 1
+    fi
+    echo "Deploying docker image version '${DOCKER_TAG}'..."
+    
+    apk add openssh
+    mkdir -p ~/.ssh
+    cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
+    chmod 600 "$SSH_PRIVATE_KEY"
+    
+    ssh -i "$SSH_PRIVATE_KEY" "$SSH_LOGIN" sh -s <<SSHCOMMANDS
+      cd $DOCKER_DIRECTORY_PROD && \
+      sed -i 's|\(image: '"${CI_REGISTRY}"'/th-wiki/th-wiki-ui:\).*|\1'"${DOCKER_TAG}"'|' docker-compose.yml && \
+      docker compose pull && \
+      docker compose up -d
+    SSHCOMMANDS
   cache: []
   when: manual
